package com.facci.jhs.persistence;
// Generated 15-jun-2015 14:57:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String codigo;
     private String icono;
     private Integer orden;
     private Set recursos = new HashSet(0);

    public Grupo() {
    }

	
    public Grupo(int id) {
        this.id = id;
    }
    public Grupo(int id, String nombre, String codigo, String icono, Integer orden, Set recursos) {
       this.id = id;
       this.nombre = nombre;
       this.codigo = codigo;
       this.icono = icono;
       this.orden = orden;
       this.recursos = recursos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }
    public Set getRecursos() {
        return this.recursos;
    }
    
    public void setRecursos(Set recursos) {
        this.recursos = recursos;
    }




}


