package com.facci.jhs.persistence;
// Generated 15-jun-2015 14:57:13 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LogActividades generated by hbm2java
 */
public class LogActividades  implements java.io.Serializable {


     private int id;
     private String metodo;
     private String accion;
     private Date fecha;
     private Boolean visible;

    public LogActividades() {
    }

	
    public LogActividades(int id) {
        this.id = id;
    }
    public LogActividades(int id, String metodo, String accion, Date fecha, Boolean visible) {
       this.id = id;
       this.metodo = metodo;
       this.accion = accion;
       this.fecha = fecha;
       this.visible = visible;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getMetodo() {
        return this.metodo;
    }
    
    public void setMetodo(String metodo) {
        this.metodo = metodo;
    }
    public String getAccion() {
        return this.accion;
    }
    
    public void setAccion(String accion) {
        this.accion = accion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }




}


