package com.facci.jhs.persistence;
// Generated 15-jun-2015 14:57:13 by Hibernate Tools 4.3.1



/**
 * Parametros generated by hbm2java
 */
public class Parametros  implements java.io.Serializable {


     private int id;
     private Integer valornumerico;
     private String valorcaracter;
     private String codigo;
     private Boolean activo;

    public Parametros() {
    }

	
    public Parametros(int id) {
        this.id = id;
    }
    public Parametros(int id, Integer valornumerico, String valorcaracter, String codigo, Boolean activo) {
       this.id = id;
       this.valornumerico = valornumerico;
       this.valorcaracter = valorcaracter;
       this.codigo = codigo;
       this.activo = activo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getValornumerico() {
        return this.valornumerico;
    }
    
    public void setValornumerico(Integer valornumerico) {
        this.valornumerico = valornumerico;
    }
    public String getValorcaracter() {
        return this.valorcaracter;
    }
    
    public void setValorcaracter(String valorcaracter) {
        this.valorcaracter = valorcaracter;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }




}


