package com.facci.jhs.persistence;
// Generated 15-jun-2015 14:57:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String codigo;
     private Boolean activo;
     private Set perfilrecursos = new HashSet(0);
     private Set perfilusuarios = new HashSet(0);

    public Perfil() {
    }

	
    public Perfil(int id) {
        this.id = id;
    }
    public Perfil(int id, String nombre, String codigo, Boolean activo, Set perfilrecursos, Set perfilusuarios) {
       this.id = id;
       this.nombre = nombre;
       this.codigo = codigo;
       this.activo = activo;
       this.perfilrecursos = perfilrecursos;
       this.perfilusuarios = perfilusuarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public Set getPerfilrecursos() {
        return this.perfilrecursos;
    }
    
    public void setPerfilrecursos(Set perfilrecursos) {
        this.perfilrecursos = perfilrecursos;
    }
    public Set getPerfilusuarios() {
        return this.perfilusuarios;
    }
    
    public void setPerfilusuarios(Set perfilusuarios) {
        this.perfilusuarios = perfilusuarios;
    }




}


