package com.facci.jhs.persistence;
// Generated 15-jun-2015 14:57:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Recurso generated by hbm2java
 */
public class Recurso  implements java.io.Serializable {


     private int id;
     private Grupo grupo;
     private String nombre;
     private String url;
     private Boolean activo;
     private Set perfilrecursos = new HashSet(0);

    public Recurso() {
    }

	
    public Recurso(int id) {
        this.id = id;
    }
    public Recurso(int id, Grupo grupo, String nombre, String url, Boolean activo, Set perfilrecursos) {
       this.id = id;
       this.grupo = grupo;
       this.nombre = nombre;
       this.url = url;
       this.activo = activo;
       this.perfilrecursos = perfilrecursos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public Set getPerfilrecursos() {
        return this.perfilrecursos;
    }
    
    public void setPerfilrecursos(Set perfilrecursos) {
        this.perfilrecursos = perfilrecursos;
    }




}


