package com.facci.jhs.persistence;
// Generated 15-jun-2015 14:57:13 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private Facultad facultad;
     private Rol rol;
     private String nombres;
     private String alias;
     private String clave;
     private String identificacion;
     private String direccion;
     private String telefono;
     private String correo;
     private Date fechacreacion;
     private String usuariocreacion;
     private String usuariomodificacion;
     private Date fechamodificacion;
     private Boolean estado;
     private Set perfilusuarios = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int id) {
        this.id = id;
    }
    public Usuario(int id, Facultad facultad, Rol rol, String nombres, String alias, String clave, String identificacion, String direccion, String telefono, String correo, Date fechacreacion, String usuariocreacion, String usuariomodificacion, Date fechamodificacion, Boolean estado, Set perfilusuarios) {
       this.id = id;
       this.facultad = facultad;
       this.rol = rol;
       this.nombres = nombres;
       this.alias = alias;
       this.clave = clave;
       this.identificacion = identificacion;
       this.direccion = direccion;
       this.telefono = telefono;
       this.correo = correo;
       this.fechacreacion = fechacreacion;
       this.usuariocreacion = usuariocreacion;
       this.usuariomodificacion = usuariomodificacion;
       this.fechamodificacion = fechamodificacion;
       this.estado = estado;
       this.perfilusuarios = perfilusuarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Facultad getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(Facultad facultad) {
        this.facultad = facultad;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }
    public String getUsuariocreacion() {
        return this.usuariocreacion;
    }
    
    public void setUsuariocreacion(String usuariocreacion) {
        this.usuariocreacion = usuariocreacion;
    }
    public String getUsuariomodificacion() {
        return this.usuariomodificacion;
    }
    
    public void setUsuariomodificacion(String usuariomodificacion) {
        this.usuariomodificacion = usuariomodificacion;
    }
    public Date getFechamodificacion() {
        return this.fechamodificacion;
    }
    
    public void setFechamodificacion(Date fechamodificacion) {
        this.fechamodificacion = fechamodificacion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getPerfilusuarios() {
        return this.perfilusuarios;
    }
    
    public void setPerfilusuarios(Set perfilusuarios) {
        this.perfilusuarios = perfilusuarios;
    }




}


